### ISSUE TITLE
ReText freezes when attempting font change (both editor and preview)

### ISSUE THREAD

**Issue by ghost** [flathub/me.mitya57.ReText#7]
Hi. As the title says, the program freezes when attempting a font change  with both the editor and the preview.
The second either font dialog pops up, the program freezes and needs to be terminated, regardless of launching from the terminal or from the standard application launcher.
This doesn't happen with the Ubuntu repository version or the python version.

Console output (the first part prior to `^C` is the initial launch, the rest is after it froze - probably obvious)

```bash
$ flatpak run me.mitya57.ReText
Qt: Session management error: Could not open network socket
Using configuration file: /home/<username>/.var/app/me.mitya57.ReText/config/ReText project/ReText.conf
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so init failed
^C
[2:24:0327/094033.879528:FATAL:bus.cc(1226)] D-Bus connection was disconnected. Aborting.
$ Process Process-1:
Traceback (most recent call last):
File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/app/lib/python3.11/site-packages/ReText/converterprocess.py", line 72, in _converter_process_func
job = receiveObject(conn_child)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/lib/python3.11/site-packages/ReText/converterprocess.py", line 41, in receiveObject
sizeBuf = recvall(sock, 4)
^^^^^^^^^^^^^^^^
File "/app/lib/python3.11/site-packages/ReText/converterprocess.py", line 34, in recvall
raise EOFError('Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?')
EOFError: Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?
^C

```

Operating System: KDE neon 5.27 (Ubuntu 22.04 / Jammy)
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.2.0-39-generic (64-bit)
Graphics Platform: X11

**Comment by mitya57** [comment]
Interesting.
I cannot reproduce this, although my environment is GNOME, not KDE.

However from your description it seems like it's related to portals: if you run ReText normally, Qt shows the font dialog directly, but in Flatpak, it goes through the portal.

But I am curious: does this happen with other Qt apps run in Flatpak?

E.g. the random app that I just found is Clementine: if you go to Tools → Preferences → Notifications and select “Show a pretty OSD” option, then the “Choose font…“ button will become active.

**Comment by ghost** [comment]
I don't have a lot of Qt apps as Flatpaks, so I installed KWrite and it was fine. I know it's a KDE app, but Clementine had old dependencies, so I figured KWrite was good enough. 

```shell
Required runtime for org.clementine_player.Clementine/x86_64/stable (runtime/org.kde.Platform/x86_64/5.15-21.08) found in remote flathub
Do you want to install it? [Y/n]:
Info: org.kde.Platform//5.15-21.08 is end-of-life, with reason:
  We strongly recommend moving to the latest stable version of the Platform and SDK
Info: org.freedesktop.Platform.VAAPI.Intel//21.08 is end-of-life, with reason:
 org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.GL.default//21.08 is end-of-life, with reason:
 org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
```

**Comment by Mailaender** [comment]
Can you post the output of `vainfo`?

**Comment by ghost** [comment]
```bash
$ vainfo
Trying display: wayland
Trying display: x11
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.17.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.4.1
vainfo: Supported profile and entrypoints
VAProfileMPEG2Simple            : VAEntrypointVLD
VAProfileMPEG2Simple            : VAEntrypointEncSlice
VAProfileMPEG2Main              : VAEntrypointVLD
VAProfileMPEG2Main              : VAEntrypointEncSlice
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
VAProfileH264Main               : VAEntrypointVLD
VAProfileH264Main               : VAEntrypointEncSlice
VAProfileH264High               : VAEntrypointVLD
VAProfileH264High               : VAEntrypointEncSlice
VAProfileH264MultiviewHigh      : VAEntrypointVLD
VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
VAProfileH264StereoHigh         : VAEntrypointVLD
VAProfileH264StereoHigh         : VAEntrypointEncSlice
VAProfileVC1Simple              : VAEntrypointVLD
VAProfileVC1Main                : VAEntrypointVLD
VAProfileVC1Advanced            : VAEntrypointVLD
VAProfileNone                   : VAEntrypointVideoProc
VAProfileJPEGBaseline           : VAEntrypointVLD
```

**Comment by ghost** [comment]
I tried this in Debian KDE (virtual machine) and had the same issue. Maybe this is just a Plasma 5 issue?

**Comment by ghost** [comment]
@Mailaender 
Duplicate? Stale? Hardly! And I've serious doubts regarding "can't reproduce" as I've reproduced this plenty. But I've no doubt regarding "won't fix" and "not planned". 

@mitya57 You might want to pack the Flatpak yourself, if you care about this version *at all*.

No matter. I've uninstalled all versions of this program anyway.

**Comment by Mailaender** [comment]
You yourself said this also happens outside of Flatpak so it is not a sandboxing/packaging issue.

**Comment by ghost** [comment]
No. That's **not** what I said. I said it *only* happens with the Flatpak, *not* with the repo version or the python version. To quote myself --
> This doesn't happen with the Ubuntu repository version or the python version.

**Comment by Mailaender** [comment]
> I tried this in Debian KDE (virtual machine) and had the same issue. Maybe this is just a Plasma 5 issue?

Sounded like the opposite.
